### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by LeonRuddat** [tudelft-iv/view-of-delft-dataset#19] opened 2022-07-28 17:31 UTC
Hi everyone,

First of all, I want to thank you for publishing this wonderful dataset. I am currently working on reproducing the radar results (5 scans) from the paper. When I use the evaluation tool from your repo, I sometimes (not often though) get a ZeroDivisionError:

```console
Traceback (most recent call last):
  File "/home/leon/Projects/OpenPCDet/tools/eval_delft.py", line 21, in <module>
    results = evaluation.evaluate(
  File "/home/leon/Projects/OpenPCDet/vod/evaluation/evaluate.py", line 44, in evaluate
    evaluation_result.update(get_official_eval_result(gt_annotations, dt_annotations, current_class))
  File "/home/leon/Projects/OpenPCDet/vod/evaluation/kitti_official_evaluate.py", line 741, in get_official_eval_result
    mAPbbox, mAPbev, mAP3d, mAPaos, mAPbbox_R40, mAPbev_R40, mAP3d_R40, mAPaos_R40 = do_eval(
  File "/home/leon/Projects/OpenPCDet/vod/evaluation/kitti_official_evaluate.py", line 665, in do_eval
    ret = eval_class(gt_annotations, dt_annotations, current_classes, difficulties, 1,
  File "/home/leon/Projects/OpenPCDet/vod/evaluation/kitti_official_evaluate.py", line 533, in eval_class
    rets = calculate_iou_partly(dt_annotations, gt_annotations, metric, num_parts)
  File "/home/leon/Projects/OpenPCDet/vod/evaluation/kitti_official_evaluate.py", line 432, in calculate_iou_partly
    overlap_part = bev_box_overlap(gt_boxes, dt_boxes).astype(
  File "/home/leon/Projects/OpenPCDet/vod/evaluation/kitti_official_evaluate.py", line 152, in bev_box_overlap
    r_iou = rotate_iou_eval(boxes, q_boxes, criterion)
  File "/home/leon/Projects/OpenPCDet/vod/evaluation/rotate_iou_cpu.py", line 269, in rotate_iou_eval
    iou[n, k] = instance_iou_eval(query_boxes[k], boxes[n], criterion)
ZeroDivisionError: division by zero
```

I found out that the error occurs in the _sort_vertex_in_convex_polygon_ function in the _rotate_iou_cpu.py_. Somehow ``` d = math.sqrt(v[0] * v[0] + v[1] * v[1]) ``` becomes zero.
 Here is the skript that i wrote using your example:

```python
from vod.evaluation import Evaluation
import os
import wandb
from tqdm import tqdm
#wandb.init("Eval Delft", name="EvalDelft_2 ", reinit=True)
# When the instance is created, the label locations are required.
evaluation = Evaluation(test_annotation_file="/home/leon/Projects/OpenPCDet/data/kitti/training/label_2")

# Using the evaluate method, the model can be evaluated on the detection labels.
EPOCHS = []
default_dir = "/home/leon/Projects/OpenPCDet/output/kitti_models/pointpillardelftradar/default/eval/eval_with_train"
for _, dirs, _ in os.walk(default_dir):
      for dir in dirs:
            if dir.startswith("epoch"):
                  EPOCHS.append(dir)

EPOCHS.sort()
for epoch in tqdm(EPOCHS):
      results = evaluation.evaluate(
          result_path=os.path.join(default_dir, epoch, "val/final_result/data"),
          current_class=[0, 1, 2])

      print("Results: \n"
            f"Entire annotated area: \n"
            f"Car: {results['entire_area']['Car_3d_all']} \n"
            f"Pedestrian: {results['entire_area']['Pedestrian_3d_all']} \n"
            f"Cyclist: {results['entire_area']['Cyclist_3d_all']} \n"
            f"mAP: {(results['entire_area']['Car_3d_all'] + results['entire_area']['Pedestrian_3d_all'] + results['entire_area']['Cyclist_3d_all']) / 3} \n"
            f"Driving corridor area: \n"
            f"Car: {results['roi']['Car_3d_all']} \n"
            f"Pedestrian: {results['roi']['Pedestrian_3d_all']} \n"
            f"Cyclist: {results['roi']['Cyclist_3d_all']} \n"
            f"mAP: {(results['roi']['Car_3d_all'] + results['roi']['Pedestrian_3d_all'] + results['roi']['Cyclist_3d_all']) / 3} \n"
            )
```
Except for the accidentally swapped input for the Eval function (has been merged into the master in the meantime) I have not changed anything in the code. The training process itself runs smoothly. (I followed your guidelines &#8594;  not quite reached the benchmark though). Not sure if I'm doing something wrong.... Have any of you ever had such a problem, or any idea what the problem could be ?
Thanks in advance!
Best Regards
Leon

**Comment by BalazsSzekeres** [comment] 2022-08-17 09:52
Hi @LeonRuddat 

Could you share the files for which the zero-division occurred?

We have a fix in the pipeline and want to make sure it fixes the problem in your case as well.

**Comment by LeonRuddat** [comment] 2022-08-17 12:57
Hi @BalazsSzekeres 

of course, here is a drive link to the epoch where the error occurred. In total, the error has occurred 4 times so far. Unfortunately, I did not save the data of the other three times. But the error should be of the same origin, because it always appeared in the same place.

It would be nice if you could let me know what exactly triggered the error. Just out of interest :)

https://drive.google.com/drive/folders/1v6LBOxWSKki8mk8WeySdlXrYnmyFqUnf?usp=sharing

Leon

**Comment by BalazsSzekeres** [comment] 2022-08-18 09:45
Hi Leon,

Can confirm the issue is now fixed. 

Debugging was a bit more annoying as we compile the code for better performance using the Numba package. Within the rotation calculation file, there is a method that handles polygons. In case the polygon is of poor quality, a distance function returns zero, which is then used for division, thus causing the exception. 

In case the numba compiler is not used, python can handle the exception.

The updated pip package you can find here with version number 1.0.3: https://pypi.org/project/vod-tudelft/

**Closed by BalazsSzekeres** 2022-08-18 09:45 UTC
Labels: bug

**Comment by LeonRuddat** [comment] 2022-08-18 15:41
Allright, thanks for your help and the detailed explanation. It works for me now too.

**Comment by Petros626** [comment] 2025-05-15 13:06
@LeonRuddat, @BalazsSzekeres  Hey, did you encountered this error? The `d3_box_overlap` throws this error, although my labels are in the correct format. I try to pre-test gt's vs. gt's.

Format:
```txt
Car 0.0 0 1.85 387.63 181.54 423.81 203.12 1.67 1.87 3.69 -16.53 2.39 58.49 1.57 -1.0
Cyclist 0.0 3 -1.65 676.6 163.95 688.98 193.93 1.86 0.60 2.02 4.59 1.32 45.84 -1.55 -1.0
```
Error:

```txt
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[1], line 10
      7 evaluation = Evaluation(test_annotation_file=os.path.join(gt_path)) # here gtlabels
      9 # Using the evaluate method, the model can be evaluated on the detection labels.
---> 10 results = evaluation.evaluate(
     11     result_path=os.path.join(gt_path), # here detection labels
     12     current_class=[0, 1, 2]) # Car, Pedestrian, Cyclist
     14 # print("Results: \n"
     15 #       f"Entire annotated area: \n"
     16 #       f"Car 3D: {results['entire_area']['Car_3d_all']} \n"
   (...)
     28 #                results['entire_area']['Cyclist_bev_all']) / 3} \n"
     29 #       )

File ~/view-of-delft-dataset/vod/evaluation/evaluate.py:45, in Evaluation.evaluate(self, result_path, current_class, score_thresh)
     43 evaluation_result = {}
     44 # kitti
---> 45 evaluation_result.update(get_official_eval_result(gt_annotations, dt_annotations, current_class, custom_method=0))
     46 # kitti roi
     47 #evaluation_result.update(get_official_eval_result(gt_annotations, dt_annotations, current_class, custom_method=3))
     49 return evaluation_result

File ~/view-of-delft-dataset/vod/evaluation/kitti_official_evaluate.py:774, in get_official_eval_result(gt_annotations, dt_annotations, current_classes, pr_detail_dict, custom_method)
    771             compute_aos = True
    772         break
--> 774 mAPbbox, mAPbev, mAP3d, mAPaos, mAPbbox_R40, mAPbev_R40, mAP3d_R40, mAPaos_R40 = do_eval(
    775     gt_annotations, dt_annotations, current_classes, min_overlaps, compute_aos, pr_detail_dict=pr_detail_dict,
    776     custom_method=custom_method)
    778 ret_dict = {}
    779 for j, curcls in enumerate(current_classes):
    780     # mAP threshold array: [num_min_overlap, metric, class]
    781     # mAP result: [num_class, num_diff, num_min_overlap]
    782     # evaluates only overlap_0_5
    783     #for i in range(1, 2):  # min_overlaps.shape[0]):
    784     # evaluates over overlap_0_5 and overlap_0_7

File ~/view-of-delft-dataset/vod/evaluation/kitti_official_evaluate.py:700, in do_eval(gt_annotations, dt_annotations, current_classes, min_overlaps, compute_aos, pr_detail_dict, custom_method)
    697 if pr_detail_dict is not None:
    698     pr_detail_dict['bev'] = ret['precision']
--> 700 ret = eval_class(gt_annotations, dt_annotations, current_classes, difficulties, 2,
    701                  min_overlaps, custom_method=custom_method)
    702 print("mAP 3D BBox finished")
    703 mAP_3d = get_m_ap(ret["precision"])

File ~/view-of-delft-dataset/vod/evaluation/kitti_official_evaluate.py:603, in eval_class(gt_annotations, dt_annotations, current_classes, difficulties, metric, min_overlaps, compute_aos, num_parts, custom_method)
    599     ignored_dets_part = np.concatenate(
    600         ignored_dets[idx:idx + num_part], 0)
    601     ignored_gts_part = np.concatenate(
    602         ignored_gts[idx:idx + num_part], 0)
--> 603     fused_compute_statistics(
    604         parted_overlaps[j],
    605         pr,
    606         total_gt_num[idx:idx + num_part],
    607         total_dt_num[idx:idx + num_part],
    608         total_dc_num[idx:idx + num_part],
    609         gt_datas_part,
    610         dt_datas_part,
    611         dc_datas_part,
    612         ignored_gts_part,
    613         ignored_dets_part,
    614         metric,
    615         min_overlap=min_overlap,
    616         thresholds=thresholds,
    617         compute_aos=compute_aos)
    618     idx += num_part
    619 for i in range(len(thresholds)):

File ~/view-of-delft-dataset/vod/evaluation/kitti_official_evaluate.py:388, in fused_compute_statistics(overlaps, pr, gt_nums, dt_nums, dc_nums, gt_datas, dt_datas, dontcares, ignored_gts, ignored_dets, metric, min_overlap, thresholds, compute_aos)
    386 ignored_det = ignored_dets[dt_num:dt_num + dt_nums[i]]
    387 dontcare = dontcares[dc_num:dc_num + dc_nums[i]]
--> 388 tp, fp, fn, similarity, _ = compute_statistics_jit(
    389     overlap,
    390     gt_data,
    391     dt_data,
    392     ignored_gt,
    393     ignored_det,
    394     dontcare,
    395     metric,
    396     min_overlap=min_overlap,
    397     thresh=thresh,
    398     compute_fp=True,
    399     compute_aos=compute_aos)
    400 pr[t, 0] += tp
    401 pr[t, 1] += fp

File ~/view-of-delft-dataset/vod/evaluation/kitti_official_evaluate.py:323, in compute_statistics_jit(overlaps, gt_datas, dt_datas, ignored_gt, ignored_det, dc_bboxes, metric, min_overlap, thresh, compute_fp, compute_aos)
    321     overlaps_dt_dc = bev_box_overlap(dt_bboxes, dc_bboxes, 0)
    322 elif metric==2: # 3D
--> 323     overlaps_dt_dc = d3_box_overlap(dt_bboxes, dc_bboxes, 0)
    325 for i in range(dc_bboxes.shape[0]):
    326     for j in range(det_size):

File ~/view-of-delft-dataset/vod/evaluation/kitti_official_evaluate.py:193, in d3_box_overlap(boxes, q_boxes, criterion)
    192 def d3_box_overlap(boxes, q_boxes, criterion=-1):
--> 193     r_inc = rotate_iou_eval(boxes[:, [0, 2, 3, 5, 6]],
    194                            q_boxes[:, [0, 2, 3, 5, 6]], 2)  # r_inc calculates bev overlap
    195     d3_box_overlap_kernel(boxes, q_boxes, r_inc, criterion)
    196     return r_inc

IndexError: index 5 is out of bounds for axis 1 with size 4
```
